name: "realloc"
shortDesc: "Plugin to reallocate container resources"
longDesc: "Reallocate CPU's, memory or network bandwidth"
example: "kubectl plugin realloc --set-cpu=500m -n <namespace> <pod> -c <container>"
command: "./realloc"
flags:
  - name: "namespace"
    desc: "namespace"
    shorthand: "n"
    defValue: "default"
  - name: "pod"
    desc: "pod name"
    shorthand: "p"
    defValue: ""
  - name: "container"
    desc: "container name"
    shorthand: "c"
    defValue: ""
  - name: "set-cpu"
    desc: "set the cpu millcores"
    defValue: ""
  - name: "set-memory"
    desc: "set the memory limit"
    defValue: ""
  - name: "set-bandwidth"
    desc: "set the bandwidth limit"
    defValue: ""